apiVersion: v1
kind: Service
metadata:
  name: {{ include "miniapi-helm.fullname" . }}
  labels:
    {{- include "miniapi-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      nodePort: {{ .Values.service.nodePort}}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "miniapi-helm.selectorLabels" . | nindent 4 }}
